language: node_js

sudo: required

cache:
  directories:
    - 'node_modules'

node_js:
  - '12'
  - '13'
  - '14'

before_script:
    - mysql -u root -e "CREATE USER testuser"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO testdb"
    - mysql -u root -e "CREATE DATABASE testdb"

script:
    - cd packages/core && yarn test
    - cd packages/client && yarn test
services:
    - mysql
