# docker compose config for development environments
version: '3'
services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=tensei
    image: mysql:8
    ports:
      - 3306:3306
  postgresql:
    container_name: postgres
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: password
      - POSTGRES_DB: tensei
    image: postgres:13.4
    ports:
      - 5432:5432
volumes:
  postgres-db-data:
  mysql-db-data:
