name: MongoDB 4.0

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.0
        ports:
          - 27017:27017
    strategy:
      fail-fast: true
      max-parallel: 6
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Node.js v-${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --production=false
      - name: Build packages
        run: yarn build
      - name: Run package tests on mongodb database
        run: cd /home/runner/work/tensei/tensei/packages/tests && yarn test
        env:
          DATABASE_TYPE: mongo
