name: Other packages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 6
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Node.js v-${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --production=false
      - name: Build packages
        run: yarn build
      - name: Run express-session-mikro-orm package tests
        run: cd /home/runner/work/tensei/tensei/packages/express-session-mikro-orm && yarn test
      - name: Run @tensei/mail package tests
        run: cd /home/runner/work/tensei/tensei/packages/mail && yarn test
      - name: Run @tensei/sdk package tests
        run: cd /home/runner/work/tensei/tensei/packages/sdk && yarn test
