name: PostgresQL v11.0

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tensei
        ports:
          - 5432:5432
    strategy:
      fail-fast: true
      max-parallel: 6
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Node.js v-${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --production=false
      - name: Build packages
        run: yarn build
      - name: Run package tests on postgresql database
        run: cd /home/runner/work/tensei/tensei/packages/tests && yarn test
        env:
          DATABASE_TYPE: postgresql
