name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: tensei
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: ''
          POSTGRES_DB: tensei
        ports:
          - 5432:5432
      mongodb:
        image: mongo:4.0
        ports:
          - 27017:27017
    strategy:
      fail-fast: true
      max-parallel: 6
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Node.js v-${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Build packages
        run: yarn build
      - name: Run package tests on mysql database
        run: cd /home/runner/work/tensei/tensei/packages/tests && yarn test
        env:
          DATABASE_TYPE: mysql
          DATABASE_NAME: tensei
          DATABASE_USER: root
      - name: Run package tests on postgresql database
        run: cd /home/runner/work/tensei/tensei/packages/tests && yarn test
        env:
          DATABASE_TYPE: postgresql
          DATABASE_NAME: tensei
          DATABASE_USER: root
      - name: Run package tests on sqlite database
        run: cd /home/runner/work/tensei/tensei/packages/tests && yarn test
        env:
          DATABASE_TYPE: sqlite
          DATABASE_NAME: tensei
